### ISSUE TITLE
hw08 part 2: Soil CO2 Levels

### ISSUE THREAD

**Issue by klemmons1s** [gabd-students/emmons_kelsea#6]
I don't know about anyone else, but I can't seem to get any other years except 2006 into a chart. Can anyone take a look? Thanks

![image](https://user-images.githubusercontent.com/45860782/50739862-79ad6f80-11ab-11e9-88bd-d97f2af5745f.png)

**Comment by mtaylor-semo** [comment]
Also, instead of using `sqrt(NROW(soil2))` (which works), you can use `sqrt(n())`.  It is less typing and would still work if you had to change the name of `soil2` because you do not have to specify a tibble.

**Comment by mtaylor-semo** [comment]
I just realized you posted this to the issues of your repository. Most people will not see this. I recommend you open issues in the [public_discussion](https://github.com/SEMO-GABD/public_discussion) forum so more people will see it.

**Comment by klemmons1s** [comment]
Thanks for the advice.  I grouped but I'm thinking this is a problem further up the chain. I noticed when I originally mutated the data that the only year in the tibble was 2006.

 
![image](https://user-images.githubusercontent.com/45860782/50745879-0f6bed80-11f2-11e9-8fea-cc00e452b613.png)

**Comment by mtaylor-semo** [comment]
Go to this section of your code:

```
soil2 <- soil %>% 
  mutate(Date = january + Day,
         Year = year(Date),
         Month = month(Date, label = TRUE, abbr = TRUE)) %>% 
group_by(Year, Month)
```

Change it so that you add `Day_number` instead of `Day` to `january`. You don't need the group_by statement I suggested aerlier because you have it here. I couldn't see that in the screenshot you posted.

**Comment by klemmons1s** [comment]
That worked. Thank you!
